cc_test (
    name = 'bubble_sort_test',
    srcs = 'bubble_sort_test.cpp',
    deps = [
    ]
)

cc_test(
    name = 'merge_sort_test',
    srcs = 'merge_sort_test.cpp',
    deps = [
    ]
)

cc_test(
    name = 'insertion_sort_test',
    srcs = 'insertion_sort_test.cpp',
    deps = [
    ]
)

cc_test(
    name = 'count_reverse_pairs_test',
    srcs = 'count_reverse_pairs_test.cpp',
    deps = [
    ]
)

cc_test(
    name = 'find_max_subarray_test',
    srcs = 'find_max_subarray_test.cpp',
    deps = [
    ]
)
